### ISSUE TITLE
[ProtoXtruder 2.0] Missing tensioning spring/knob?

### ISSUE THREAD

**Issue by benbender** [nhchiu/3DPrinter-Designs#1]
Hey,

first and foremost: Thanks for your amazing work! <3

I'm just looking at the ProtoXtruder 2.0 and I'm missing the tensioning spring and knob. Are they included in the gear kit or are they missing from the BOM?

**Comment by nhchiu** [comment]
> Hey,
> 
> first and foremost: Thanks for your amazing work! <3
> 
> I'm just looking at the ProtoXtruder 2.0 and I'm missing the tensioning spring and knob. Are they included in the gear kit or are they missing from the BOM?

Hi! Thanks for asking.
It should be included in the gear kit. (You can double check with the seller)
I forgot to have it listed in the BOM. I'll fix it later. Thanks for catching that!
